[files]
extend-exclude = [
    ".git/",
    "lang/",
    "public/build/assets",
    # Lorem ipsum
    "content/collections/pages/long-form-content.md",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\b[0-9a-f]{8}\\b"
]

[default.extend-words]
"tpyo" = "tpyo"
