<template><h1 id="installation" tabindex="-1"><a class="header-anchor" href="#installation" aria-hidden="true">#</a> Installation</h1>
<h2 id="installation-via-the-cli" tabindex="-1"><a class="header-anchor" href="#installation-via-the-cli" aria-hidden="true">#</a> Installation via the CLI</h2>
<p>The easiest way to install Statamic together with Peak is to use the <a href="https://github.com/statamic/cli" target="_blank" rel="noopener noreferrer">official CLI<OutboundLink/></a>. Install the CLI by running <code>composer global require statamic/cli</code> and for each project just run <code>statamic new my-site</code> and pick Peak as a starter kit. Alternatively you can skip this manual selection by running: <code>statamic new my-site studio1902/statamic-peak</code> (3.2 CLI only).</p>
<p>Make sure you use the provided <code>.env.example</code> file by running <code>cp .env.example .env &amp;&amp; php artisan key:generate</code>.</p>
<h2 id="install-into-an-existing-statamic-v3-2-project" tabindex="-1"><a class="header-anchor" href="#install-into-an-existing-statamic-v3-2-project" aria-hidden="true">#</a> Install into an existing Statamic v3.2+ project</h2>
<p>If you already have an existing Statamic installation you can run the following command: <code>php please starter-kit:install studio1902/statamic-peak</code>.</p>
<h2 id="compile-the-frontend-assets" tabindex="-1"><a class="header-anchor" href="#compile-the-frontend-assets" aria-hidden="true">#</a> Compile the frontend assets</h2>
<p>The starter kit comes bundles with compiled assets. Run <code>npm i &amp;&amp; npm run dev</code> to compile your frontend assets. Use <code>npm run watch</code> to watch and compile whenever you made any changes.</p>
<p>Since we use the Tailwind CSS JIT compiler, as soon as you make changes you need to compile them yourself. Compilation is configured in <code>webpack.mix.js</code>. Make sure you add your hostname to your <code>.env</code> file (<code>APP_URL</code>) as it's being used for Browsersync in <code>webpack.mix.js</code>.</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">npm</span> i <span class="token operator">&amp;&amp;</span> <span class="token function">npm</span> run <span class="token function">watch</span> <span class="token punctuation">(</span>or <span class="token function">npm</span> run dev<span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>To compile for production run this (on your server). Since Peak uses the Tailwind CSS JIT compiler this won't purge anything, but it will minify your assets:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">npm</span> run production
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div></template>
