<template><h1 id="start-out-on-top" tabindex="-1"><a class="header-anchor" href="#start-out-on-top" aria-hidden="true">#</a> Start out on top!</h1>
<p>Peak is your personal development sherpa. It's an opinionated starter kit for all your Statamic sites. It's design agnostic but comes bundled with tools like Tailwind CSS and AlpineJS and a workflow you can use to build anything you want. Peak features a page builder, a rich collection of starter templates, fieldsets, blueprints, SEO functionality, configuration and more to get you started on your clients' site straight away. Peak is easy to extend or edit to fit your clients' website needs and will drastically improve your development speed.</p>
<p>The aim of Peak is to make it easy to start new projects as they often share much of the same principles. Whether you're new to Statamic or a veteran, there will be something interesting in here for you. Please participate and discuss on how to make our websites better.</p>
<p>Maintaining Peak demands a lot of my time and it probably saves you a lot. Your sponsoring would mean a great deal to me as it makes it much easier for me to maintain this project and keep improving it. <a href="https://github.com/sponsors/studio1902" target="_blank" rel="noopener noreferrer">Sponsor me<OutboundLink/></a>.</p>
<h3 id="extendible-page-builder-and-long-form-content-with-sets" tabindex="-1"><a class="header-anchor" href="#extendible-page-builder-and-long-form-content-with-sets" aria-hidden="true">#</a> Extendible page builder and long form content with sets</h3>
<p><img src="https://cdn.studio1902.nl/assets/statamic-peak/statamic-peak-promo-01.png" alt="Extendible page builder and long form content with sets."></p>
<h3 id="generate-custom-social-images-and-browser-appearance" tabindex="-1"><a class="header-anchor" href="#generate-custom-social-images-and-browser-appearance" aria-hidden="true">#</a> Generate custom social images and browser appearance</h3>
<p><img src="https://cdn.studio1902.nl/assets/statamic-peak/statamic-peak-promo-02.png" alt="Generate custom social images and browser appearance configuration and generate favicons."></p>
<h3 id="professional-seo-per-entry-and-globally" tabindex="-1"><a class="header-anchor" href="#professional-seo-per-entry-and-globally" aria-hidden="true">#</a> Professional SEO, per entry and globally.</h3>
<p><img src="https://cdn.studio1902.nl/assets/statamic-peak/statamic-peak-promo-03.png" alt="Professional SEO, per entry and globally."></p>
<h3 id="configure-trackers-and-add-a-gprd-compliant-cookie-banner" tabindex="-1"><a class="header-anchor" href="#configure-trackers-and-add-a-gprd-compliant-cookie-banner" aria-hidden="true">#</a> Configure trackers and add a GPRD compliant cookie banner</h3>
<p><img src="https://cdn.studio1902.nl/assets/statamic-peak/statamic-peak-promo-04.png" alt="Configure trackers, add a GPDR compliant cookie banner."></p>
<h3 id="social-media-integration-and-301-302-redirects" tabindex="-1"><a class="header-anchor" href="#social-media-integration-and-301-302-redirects" aria-hidden="true">#</a> Social media integration and 301/302 redirects</h3>
<p><img src="https://cdn.studio1902.nl/assets/statamic-peak/statamic-peak-promo-05.png" alt="Social media integration and 301/302 redirects."></p>
<h3 id="a-lot-more-additional-bottles-of-oxygen" tabindex="-1"><a class="header-anchor" href="#a-lot-more-additional-bottles-of-oxygen" aria-hidden="true">#</a> A lot more additional bottles of oxygen</h3>
<p><img src="https://cdn.studio1902.nl/assets/statamic-peak/statamic-peak-promo-06.png" alt="And a lot more additional bottles of oxygen."></p>
<p>The Peak branding is done by Jouke Zult from <a href="https://mistralmerkactivisten.nl" target="_blank" rel="noopener noreferrer">Mistral Merkactivisten<OutboundLink/></a>. Thank you so much!</p>
</template>
